name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: start the app
        run: |
          npm install --legacy-peer-deps
          npm start
          ls
